@startuml
title SmartHome Web Application Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(SmartHomeSystem, "SmartHome System") {
  Container(ObservationApplication, "Observation Application", "Java, Spring", "Observation monitoring and control application")
  Container(ObservationDatabase, "Observation Database", "PostgreSQL", "Stores Observations data")
}

Container(ObservationApplication, "Observation Application", "Java, Spring") {
  Component(ObservationController, "ObservationController", "The technical layer is the controller")
  Component(ObservationService, "ObservationService", "The technical layer is the service")
  Component(ObservationRepository, "ObservationRepository", "The technical layer is the repository")
}

Rel(ObservationController,ObservationService,"Calls Observation business logic")
Rel(ObservationService,ObservationRepository,"Reads/Writes data")
Rel(ObservationRepository,ObservationDatabase,"Reads/Writes Observation data", TCP/SQL)
@enduml